env:
  browser: true
  commonjs: true
  es6: true
  node: true
extends: 'eslint:recommended'
parser: 'babel-eslint'
parserOptions:
  ecmaFeatures:
    experimentalObjectRestSpread: true
    jsx: true
  sourceType: module
plugins:
  - react
  - flowtype
rules:
  indent:
    - 2
    - 2
  linebreak-style:
    - 2
    - unix
  quotes:
    - 2
    - double
    - avoid-escape
  semi:
    - 2
    - always
  "flowtype/space-after-type-colon":
    - 1
    - always
  "flowtype/space-before-type-colon":
    - 1
    - never
